### ISSUE TITLE
Occasional timeout during e2e tests

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-exec#241]
Tests will occasionally time out with the following output:

```
=== RUN   TestWorkspace_multiple/workspaces-1.1.0-alpha20211006/select_non-default_workspace
=== CONT  TestWorkspace_multiple/workspaces-1.1.0-alpha20211006
    util_test.go:113: [INFO] running Terraform command: C:\Users\circleci\AppData\Local\Temp\terraform_3475341054\terraform.exe workspace select -no-color foo
    util_test.go:113: [INFO] running Terraform command: C:\Users\circleci\AppData\Local\Temp\terraform_3475341054\terraform.exe workspace list -no-color
panic: test timed out after 15m0s

goroutine 3204 [running]:
testing.(*M).startAlarm.func1()
	C:/Program Files/Go/src/testing/testing.go:1788 +0x8e
created by time.goFunc
	C:/Program Files/Go/src/time/sleep.go:180 +0x31
 [... 5000 lines]
goroutine 3184 [chan receive (nil chan)]:
github.com/hashicorp/terraform-exec/tfexec.(*Terraform).runTerraformCmd.func1()
	C:/Users/circleci/project/tfexec/cmd_default.go:18 +0x49
created by github.com/hashicorp/terraform-exec/tfexec.(*Terraform).runTerraformCmd
	C:/Users/circleci/project/tfexec/cmd_default.go:17 +0x211

goroutine 3218 [runnable, locked to thread]:
syscall.Syscall(0x7ffe84d6e810, 0x2, 0x768, 0x0, 0x0)
	C:/Program Files/Go/src/runtime/syscall_windows.go:479 +0xf4
syscall.CancelIoEx(0xc00142af28, 0x0)
	C:/Program Files/Go/src/syscall/zsyscall_windows.go:474 +0x71
internal/poll.(*FD).Close(0xc001e9fb80)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:391 +0x45
os.(*file).close(0xc001e9fb80)
	C:/Program Files/Go/src/os/file_windows.go:197 +0x56
os.(*File).Close(...)
	C:/Program Files/Go/src/os/file_posix.go:26
os/exec.(*Cmd).writerDescriptor.func1()
	C:/Program Files/Go/src/os/exec/exec.go:312 +0x57
os/exec.(*Cmd).Start.func1(0xc000249f20)
	C:/Program Files/Go/src/os/exec/exec.go:441 +0x25
created by os/exec.(*Cmd).Start
	C:/Program Files/Go/src/os/exec/exec.go:440 +0x8e5
FAIL	github.com/hashicorp/terraform-exec/tfexec/internal/e2etest	900.916s
FAIL
```

The above was observed as an intermittent failure during a CI run: https://app.circleci.com/pipelines/github/hashicorp/terraform-exec/1281/workflows/c0799273-2d14-42cb-95f5-0e23ff8da447/jobs/15618
It has been seen on both Windows and Linux.

Needs reproduction.

**Comment by kmoe** [comment]
Haven't seen this for a while.
